# docker-compose.yml
 
services:
#  contenedor:
#    image: python:3.10-alpine
#    volumes:
#      - ./ejercicios:/ejercicios
#    working_dir: /ejercicios
  app:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
