# docker-compose.yml
version: "3" 

services:
  app:
    build: .
    depends_on:
      - mongo
    ports:
      - 5000:5000
    volumes:
      - ./app:/app

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./dump:/dump
      - ./datos_db:/data/db

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_URL="mongodb://mongo:27017"
    
  web:
    build: .
    volumes:
      - ./app:/app
      - ./dump:/dump
    ports:
      - 8000:8000
    command: python mi_sitio/manage.py runserver 0.0.0.0:8000