# Generated by Django 4.1.1 on 2022-12-11 17:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='titulo', editable=False, populate_from='nombre'),
            preserve_default=False,
        ),
    ]
