POST http://localhost:5000/api/recipes HTTP/1.1
content-type: application/json

{
  "name": "Receta Inventada 1",
  "ingredients": [
    { "name": "Ingrediente 1", "quantity": { "value": 1, "unit": "dash" } }
  ],
  "garnish": "Lemon Twist",
  "instructions": [
    "Combine ingredients and stir with ice.",
    "Garnish with lemon twist."
  ],
  "slug": "receta-inventada-1"
}